# Generated by Django 3.2 on 2021-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='send_to_manager',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='access_request',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='issued',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
