# Generated by Django 3.2 on 2021-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20210416_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='access_request',
            field=models.CharField(choices=[('Not Sent', 'Not Sent'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], db_index=True, max_length=10),
        ),
    ]
